package com.business.aiagent.service;

import com.business.aiagent.dto.StrategicReportResponse;
import com.business.aiagent.entity.StrategicReport;
import com.business.aiagent.entity.User;
import com.business.aiagent.repository.StrategicReportRepository;
import com.business.aiagent.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
public class StrategicReportService {
    
    private final StrategicReportRepository reportRepository;
    private final UserRepository userRepository;
    
    @Transactional
    public StrategicReportResponse generateReport(String username, String title, String reportType, String context) {
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new RuntimeException("User not found"));
        
        // TODO: Call Python AI service to generate actual strategic analysis
        // For now, create a placeholder report
        String recommendations = "Strategic recommendations will be generated by AI service based on analyzed documents and business data.";
        String marketInsights = "Market insights and competitive analysis will be provided by the AI service.";
        
        StrategicReport report = new StrategicReport();
        report.setUser(user);
        report.setTitle(title);
        report.setReportType(reportType);
        report.setRecommendations(recommendations);
        report.setMarketInsights(marketInsights);
        
        StrategicReport saved = reportRepository.save(report);
        return mapToResponse(saved);
    }
    
    public Page<StrategicReportResponse> getUserReports(String username, Pageable pageable) {
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new RuntimeException("User not found"));
        
        return reportRepository.findByUserOrderByCreatedAtDesc(user, pageable)
                .map(this::mapToResponse);
    }
    
    public StrategicReportResponse getReport(Long id, String username) {
        StrategicReport report = reportRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Report not found"));
        
        if (!report.getUser().getUsername().equals(username)) {
            throw new RuntimeException("Access denied");
        }
        
        return mapToResponse(report);
    }
    
    @Transactional
    public void deleteReport(Long id, String username) {
        StrategicReport report = reportRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Report not found"));
        
        if (!report.getUser().getUsername().equals(username)) {
            throw new RuntimeException("Access denied");
        }
        
        reportRepository.delete(report);
    }
    
    private StrategicReportResponse mapToResponse(StrategicReport report) {
        return new StrategicReportResponse(
                report.getId(),
                report.getTitle(),
                report.getReportType(),
                report.getSwotAnalysis(),
                report.getRecommendations(),
                report.getMarketInsights(),
                report.getRiskAssessment(),
                report.getCreatedAt()
        );
    }
}
